name       : ptex
version    : 2.4.1
release    : 1
source     :
    - https://github.com/wdas/ptex/archive/refs/tags/v2.4.1.tar.gz : 664253b84121251fee2961977fe7cf336b71cd846dc235cd0f4e54a0c566084e
homepage   : https://ptex.us/
license    : BSD-3-Clause
component  : programming.library
summary    : Per-Face Texture Mapping for Production Rendering
description: |
    Ptex is a texture mapping system developed by Walt Disney Animation Studios for production-quality rendering.
clang      : yes
setup      : |
    %patch -p1 < $pkgfiles/cmake-libptex-soname.patch
    %cmake_ninja \
        -DPTEX_BUILD_STATIC_LIBS=OFF \
        -DCMAKE_SKIP_RPATH=ON \
        -DPTEX_VER=%version% \
        -DPTEX_SHA=release
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    export LD_LIBRARY_PATH=$installdir/usr/lib64
    %ninja_check
